#!/usr/bin/env bash

if [ $# -ne 2 ]
then
    >&2 echo "usage: libfind SYMBOL ROOTPATH"
    exit 1
fi

SYMBOL=$1
ROOTPATH=$2

for candidate in $(find $ROOTPATH -type f 2>&1 | egrep '\.(a|o|so|dylib)$')
do
    count=$(nm -g $candidate 2>&1 | grep $SYMBOL | wc -l)
    if [ $count != 0 ]
    then
        echo $candidate
    fi
done
